### ISSUE TITLE
Working with non html messages

### ISSUE THREAD

**Issue by AquiGorka** [aakashlpin/emailapi#38]
Hello there, very nice tool. I was reading the code to learn how you specify which values correspond to which keys and saw that you are using `css` path/references. Does this mean this tool won't work on text only messages?

**Comment by AquiGorka** [comment]
@aakashlpin any thoughts on this?

**Comment by aakashlpin** [comment]
@AquiGorka You're right. The data extraction from emails works only with HTML email and not text based emails at the moment. TBH, I don't know how you'd "define" which values to extract from text based emails given they lack a/any structure. You might be able to run one-off data extraction tasks, but that isn't the purpose with emailapi.

Open to hearing your thoughts and how you'd approach solving this? Interesting problem statement though.

**Comment by AquiGorka** [comment]
@aakashlpin thank you for clarifying.
Yes, non-html messages lack the structure and that's what makes it hard, for messages that won't change over time maybe regexes could be used - or if a project can afford it, then GPT3 can very much help in that realm of making structured data from unstructured data.
